TechnocademyWebSolution/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TechnocademyWebSolution.Models
{
    public class Category
    {
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public  int CourseId { get; set; }
    }
}

TechnocademyWebSolution/Controllers/CategoryController.cs
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TechnocademyWebSolution.Models;

namespace TechnocademyWebSolution.Controllers
{
    public class CategoryController : Controller
    {
        private ProjectDB db = new ProjectDB();
      
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetAllCategories()
        {
            var categories = db.Categories.ToList();
            return Json(categories, JsonRequestBehavior.AllowGet);
        }
        
        [HttpPost]
        public JsonResult Create([Bind(Include = "CategoryId,CategoryName,CourseId")] Category model)
        {
            var categoryList = db.Categories.ToList();

            if (categoryList.Any(c => c.CategoryName == model.CategoryName))
            {
                return Json("no", JsonRequestBehavior.AllowGet);
            }
            
            if (ModelState.IsValid)
            {
                db.Categories.Add(model);
                db.SaveChanges();
               
                return Json(model, JsonRequestBehavior.AllowGet);
            }
            throw new HttpException(404, "There were error in your database");
        }
       
        [HttpPost]
        public JsonResult Edit([Bind(Include = "CategoryId,CategoryName,CourseId")] Category model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return Json(model, JsonRequestBehavior.AllowGet);
            }
            throw new HttpException(404, "There were error in your database");
        }

        public JsonResult DeleteConfirmed(int id)
        {
            var existing = db.Categories.Find(id);

            if (existing != null)
            {
                db.Categories.Remove(existing);
                db.SaveChanges();
                return Json("ok", JsonRequestBehavior.AllowGet);
            }
            throw new HttpException(404, "There were error in your database");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TechnocademyWebSolution/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using TechnocademyWebSolution.Models;

namespace TechnocademyWebSolution.Controllers
{
    public class CourseController : Controller
    {
        private ProjectDB db = new ProjectDB(); 
        // GET: Course
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetAllCourses()
        {
            var courses = db.Courses.ToList();
            return Json(courses, JsonRequestBehavior.AllowGet);
        }
       

        [HttpPost]
        public JsonResult Create([Bind(Include = "CourseId,CourseName")]Course model)
        {
            var courseList = db.Courses.ToList();

            if (courseList.Any(course => course.CourseName == model.CourseName))
            {
                return Json("no", JsonRequestBehavior.AllowGet);
            }
            
            if (ModelState.IsValid)
            {
                db.Courses.Add(model);
                db.SaveChanges();
                return Json(model, JsonRequestBehavior.AllowGet);
            }

            throw new HttpException(404, "There were error in your database");
        }

        [HttpPost]
        public JsonResult Edit([Bind(Include = "CourseId,CourseName")]Course model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return Json(model, JsonRequestBehavior.AllowGet);
            }
            throw new HttpException(404, "There were error in your database");
        }

        public JsonResult DeleteConfirmed(int id)
        {
            var existing = db.Courses.Find(id);

            if (existing != null)
            {
                db.Courses.Remove(existing);
                db.SaveChanges();
                return Json("ok", JsonRequestBehavior.AllowGet);
            }
            throw new HttpException(404, "There were error in your database");
        }
    }
}

TechnocademyWebSolution/Views/Category/Index.cshtml
@{
    ViewBag.Title = "Category";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div>&nbsp;&nbsp;</div>

<div class="panel panel-success" ng-controller="categoryController">
    <div class="panel-heading">
        <h3 class="panel-title">{{categoryName}} List</h3>
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Category Name</th>
                        <th>Course Name</th>
                        <th>Action</th>
                    </tr>
                </thead>

                <tbody ng-repeat="category in categoryList" ng-init="row={}" ng-switch="row.edit">

                    <tr ng-switch-default>
                        <td>{{category.CategoryName}}</td>

                        <td ng-repeat="course in courseList" ng-if="course.CourseId == category.CourseId">
                            {{course.CourseName}}
                        </td>

                        <td>
                            <button type="button" class="btn btn-danger btn-sm" ng-click="DeleteCategory($index,category.CategoryId)">
                                <span class="glyphicon glyphicon-trash"></span> Trash
                            </button>
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <button type="button" class="btn btn-warning btn-sm" ng-click="category.CategoryName;row.edit=true">
                                <span class="glyphicon glyphicon-edit"></span> Edit
                            </button>
                        </td>
                        @*<td><a ng-href="@Url.Action("Delete", "Course")/{{id = course.CourseId}}" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-trash"></span></a></td>*@
                    </tr>

                    <tr ng-switch-when="true">
                        <td>
                            <div class="input-group">
                                <span class="input-group-addon" id="categoryName">Category Name</span>
                                <input type="text" class="form-control" ng-model="category.CategoryName" ng-value="category.CategoryName" aria-describedby=" categoryname">
                            </div>
                        </td>
                        <td>
                            <label>Course:</label>
                            <select ng-model="category.CourseId">
                                <option ng-repeat="option in courseList" value="{{option.CourseId}}">{{option.CourseName}}</option>
                            </select>

                        </td>
                        <td>
                            <button type="button" class="btn btn-success btn-sm" ng-click="EditCategory(category);row.edit=false">
                                <span class="glyphicon glyphicon-save"></span> Save
                            </button>
                        </td>
                    </tr>

                    <tr ng-if="categoryList.length==0">
                        <td colspan="4" class="text-center">There have no Courses to display.</td>
                    </tr>

                </tbody>
            </table>
        </div>
    </div>
    <div class="panel-footer">
        <table class="table table-striped table-bordered">
            <tbody>
                <tr ng-if="states.showCategoryForm">
                    <td>
                        <div class="input-group">
                            <span class="input-group-addon" id="addCategoryName">Category Name</span>
                            <input type="text" class="form-control" placeholder="Category Name" ng-model="new.Category.CategoryName" aria-describedby="addCategoryname">
                        </div>
                        <div class="validation-summary-errors" ng-if="states.errorCategory">Please field required for category and course.</div>
                    </td>

                    <td>
                        <div>
                            <label> Course: </label>
                            <select ng-model="new.Category.CourseId">
                                <option value="">Select Course</option>
                                <option ng-repeat="option in courseList" value="{{option.CourseId}}">{{option.CourseName}}</option>
                            </select>
                        </div>
                    </td>

                    <td>
                        <button type="button" class="btn btn-primary" ng-click="addCategory()"> Add</button>
                        <button type="button" class="btn btn-default" ng-click="showCategoryForm(false)">Cancel</button>
                    </td>
                </tr>
            </tbody>
        </table>
        <a ng-click="showCategoryForm(true)" class="btn btn-primary">Add Category</a>
    </div>
</div>


@section scripts {
    <script src="~/CustomScript/Angular/app.js"></script>
    <script src="~/CustomScript/Angular/CategoryCtrl.js"></script>
}